# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(blank=True)),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('minutes', models.TextField(blank=True)),
                ('backup', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('one_sent', models.BooleanField(default=False)),
                ('two_sent', models.BooleanField(default=False)),
                ('now_sent', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='agendas.AgendaItem')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('agenda_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agendas.Meeting'),
        ),
    ]
